---

- name: peervpn install
  hosts: all 
  gather_facts: no
  become: yes
  tasks:

    - name: Add specified repository into sources list
      apt_repository:
        repo: deb [trusted=yes] http://security.ubuntu.com/ubuntu bionic-security main
        state: present

    - name: Update repositories cache and install needed packages
      apt:
        name:
          - make
          - gcc
          - libssl1.0-dev 
          - zlib1g-dev 
          - libssl1.0-dev
          - apache2 
          - dpkg-dev
        update_cache: yes

    - name: Clone a github repository
      git:
        repo: https://github.com/peervpn/peervpn
        dest: ~/peervpn
        clone: yes
        update: yes

    - name: Build peervpn
      make:
        chdir: ~/peervpn

    - name: Make peervpn executable
      file: dest=~/peervpn/peervpn mode=a+x

    - name: Create needed directories
      file:
        path: "{{ item }}"
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: 0775
      loop:
        - ~/peervpn_1.0-1_amd64/usr/local/bin
        - ~/peervpn_1.0-1_amd64/DEBIAN
        - /var/www/html/debs/amd64

    - name: Copy control and peervpn
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: "{{ item.mode }}"
        remote_src: "{{ item.remote_src }}"
        owner: "{{ item.owner }}"
        group: "{{ item.group }}"
      with_items:
        - { src: '~/peervpn/peervpn', dest: '~/peervpn_1.0-1_amd64/usr/local/bin', mode: '0644', remote_src: 'true', owner: 'root', group: 'root'}
        - { src: '{{ control }}', dest: '~/peervpn_1.0-1_amd64/DEBIAN/control', mode: '0644', remote_src: 'false', owner: 'ubuntu', group: 'ubuntu'}

    - name: Build debian package
      shell: sudo dpkg-deb --build --root-owner-group ~/peervpn_1.0-1_amd64
        
    - name: Copy package to the local repository
      copy:
        src: ~/peervpn_1.0-1_amd64.deb
        dest: /var/www/html/debs/amd64/peervpn_1.0-1_amd64.deb
        remote_src: true

    - name: Make repository
      shell: dpkg-scanpackages amd64 | gzip -9c > amd64/Packages.gz 
      args:
         chdir: /var/www/html/debs/

    - name: Add local repository into sources list
      apt_repository:
        repo: deb [trusted=yes] http://127.0.0.1/debs amd64/
        state: present

    - name: install peervpn package from local repo
      apt:
         name: peervpn
         state: present

    - name: Set execution permission
      file:
        dest: /usr/local/bin/peervpn
        mode: 'a+x'
